config/routes.rb
Rails.application.routes.draw do
  root 'articles#new'
  resources :articles
  resources :posts
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
     mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end
  
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
  end
  
   def create
    @article = Article.new(article_params)
    if @article.save
      # logger.debug("=========================== URL = #{Article.last.image.url}")
      logger.debug("=========================== image = #{@article.image}")
      
      flash[:notice] = "Article created!"
      redirect_to articles_path
    else
      render root_url
    end
  end
  
   private
    def article_params
        params.require(:article).permit(:title, :image)
    end
  
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
     def new
    @post = Post.new
    end
  
  def index
    @posts = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end
  
   def create
    @post = Post.new(post_params)
    if @post.save
    #   logger.debug("=========================== URL = #{@post.last.image.url}")
      logger.debug("=========================== image = #{@post.image}")
      
      flash[:notice] = "post created!"
      redirect_to posts_path
    else
      render root_url
    end
    end
  
   private
    def post_params
        params.require(:post).permit(:title, :image,:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<%= article.title %><br>
　  　<%= link_to image_tag(article.image.url,:size =>'100x100'), article_path(article.id) %><br>
<% end %>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/articles/show.html.erb
<%= @article.title %><br>
<%= image_tag(@article.image.url,:size =>'300x300') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= post.title %><br>
　  　<%= link_to image_tag(post.image.url,:size =>'100x100'), post_path(post.id) %><br>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

  <div class="field">
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content, "内容" %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %>
    <%= f.file_field :image %>
  </div>
  
  <div class="actions">
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= @post.title %><br>
<%= image_tag(@post.image.url,:size =>'300x300') %>